### ISSUE TITLE
Data Exporter 0.1.0

### ISSUE THREAD

**Issue by IljaN** [owncloud/data_exporter#18]
# MVP
- [x] Bootstrap app 
- [x] Import/Export Users 
- [x] Import/Export Files 
- [x] Import/Export User Shares + Public Shares (with federated rewiring)  (~4 md)
    - [x] local share import and export, including conversion to remote share of the target user doesn't exist in destination server
    - [x] remote shares whose owner is the one we're importing
    - [x] performance improvements in the local shares (deleting the converted remote share)
    - ~~remaining work, see https://github.com/owncloud/data_exporter_old/issues/6#issuecomment-414711134 (5.5md + bigger unknowns)~~ => moved to https://github.com/owncloud/data_exporter/issues/42

- [x] Import/Export Group Shares (as is for now, no rewiring), future is here #11 (2.5md)
- [x] Test with ldap #16  (~1 md)
- ~~lock users: #6~~
- [x] document limitations: #7 
- [x] adjust README to be very clear how to use this: https://github.com/owncloud/data_exporter/issues/13
- [x] raise ticket in docs repo: https://github.com/owncloud/data_exporter/issues/37 
- [x] acceptance tests: https://github.com/owncloud/data_exporter/issues/17 https://github.com/owncloud/data_exporter/issues/36

# Customer requirements
the above and:
- ~~Import/Export Comments  (~1 md) #19~~
- ~~Import/Export Activity~~
- [x] Import/Export Versions
- ~~Import/Export trashbin #14   (~1 md)~~

moved to next version: https://github.com/owncloud/data_exporter/issues/42

**Comment by PVince81** [comment]
next version here https://github.com/owncloud/data_exporter/issues/42

**Comment by IljaN** [comment]
https://github.com/owncloud/data_exporter/releases/tag/v0.0.1

**Comment by PVince81** [comment]
the version should have been v0.1.0 as per this ticket...

anyway, next version will be 0.1.1
